# official image: https://hub.docker.com/_/mongo

version: "3"

services:
  node:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    command: sh -c "yarn && yarn start"
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27010:27017"
    volumes:
      - ./mongodb:/data/db
      - ./configdb:/data/configdb
      - ./mongod.conf:/etc/mongod.conf.orig
